services:
  db:
    image: postgres:18@sha256:74935e72241653ca55e0414067e6d8763aceb8a810eb51b452253ec3dcfc4336
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    command: ['postgres', '-c', 'wal_level=logical']
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
