engineStrict: true

allowBuilds:
  '@rocicorp/zero-sqlite3': true
  esbuild: true
  protobufjs: false

overrides:
  'esbuild@<=0.24.2': '>=0.25.0'
  'cookie@<0.7.0': '>=0.7.0'
  'validator@<13.15.20': '>=13.15.20'
  'js-yaml@>=4.0.0 <4.1.1': '>=4.1.1'
  'validator@<13.15.22': '>=13.15.22'
  'zero-svelte>@rocicorp/zero': '1.3.0'
